product_url: 'https://192.168.140.28/svn_product/vadminsite'
product_tag_dir: 'tag'
product_trunk_dir: 'trunk'
online_site_path: 'D:\com5173\vadmin.5173.com'
app_pool: 'vadmin.5173.com'
website_verified_url: 'http://vadmin.5173.com/Index.aspx?ReturnUrl=%2f'
verified_keyword: '5173'