sourcecode_urls: 
    - 'https://007.5173.com/svn/SourceCode/AdminTrading/Dev/vadmindev'
sourcecode_dirs: 
    - sourcecode

#sourcecode_username: 301645
#sourcecode_password: //5173@#q
#product_username: 301645
#product_password: //5173@#q
#online_username: zhangyfsh
#online_password: hjqipS5u95

build_batch: 'sourcecode\BuildTools\VadminBuild.bat'
GetVersion: 'sourcecode\BuildTools\GetVersion.exe'

sites:
    vadmin:
        product_url: 'https://192.168.140.28/svn_product/vadminsite/trunk/vadmin'
        product_dir: 'product\vadmin'
        online_url: 'https://subversion.5173.com/WEB/C2CV1/'
        online_dir: 'online\vadmin'
        site_dir: 'sourcecode\AdminMainUiNew'
        copy_bat: 'sourcecode\BuildTools\VadminCopy.bat'
        config: config
        web_config:
            config_test: Web.config
            config_online: Web.config
            online: Web.config