product_url: 'https://192.168.140.28/svn_product/gameidsites'
product_tag_dir: 'tag'
product_trunk_dir: 'trunk'
online_site_path: 'D:\com5173\vidadmin.5173.com'
app_pool: 'vidadmin.5173.com'
website_verified_url: 'http://vidadmin.5173.com/Index.aspx?ReturnUrl=%2fDefault.aspx'
verified_keyword: '5173'