product_url: 'https://192.168.140.28/svn_product/securitysites'
product_tag_dir: 'tag'
product_trunk_dir: 'trunk'
online_site_path: 'D:\com.5173\security.admin.5173.com'
app_pool: 'DefaultAppPool'
website_verified_url: 'http://security.admin.5173.com/f5.aspx'
verified_keyword: 'OK'