sourcecode_urls: 
    - 'http://tech.5173.com/svn/login/trunk/SecuritySolution/securitydev'
sourcecode_dirs: 
    - sourcecode

sourcecode_username: 'zhangyfsh'
sourcecode_password: 'good198696'
#product_username: 301645
#product_password: //5173@#q
#online_username: zhangyfsh
#online_password: hjqipS5u95

build_batch: 'sourcecode\BuildTools\Build.bat'
GetVersion: 'sourcecode\BuildTools\GetVersion.exe'

sites:
    security:
        product_url: 'https://192.168.140.28/svn_product/securitysites/trunk/security'
        product_dir: 'product\security'
        online_url: 'https://subversion.5173.com/WEB/PASSPORT.5173.COM/Security/SecurityWeb'
        online_dir: 'online\security'
        site_dir: 'sourcecode\FostSecurityWeb'
        copy_bat: 'sourcecode\BuildTools\SecurityCopy.bat'
        config: config
        web_config:
            config_test: web.config
            config_online: web.config
            online: Web.config

    securityadmin:
        product_url: 'https://192.168.140.28/svn_product/securitysites/trunk/securityadmin'
        product_dir: 'product\securityadmin'
        online_url: 'https://subversion.5173.com/WEB/PASSPORT.5173.COM/Security/SecurityAdminWeb'
        online_dir: 'online\securityadmin'
        site_dir: 'sourcecode\FostSecurityAdminWeb'
        copy_bat: 'sourcecode\BuildTools\SecurityAdminCopy.bat'
        config: config
        web_config:
            config_test: web.config
            config_online: web.config
            online: Web.config