product_url: 'https://192.168.140.28/svn_product/zengjinsites/trunk'
product_tag_dir: 'tag'
product_trunk_dir: 'trunk'
online_site_path: 'D:\com5173\vzengjin.5173.com'
app_pool: 'vzengjin.5173.com'
website_verified_url: 'https://passport.5173.com/?ReturnUrl=http%3a%2f%2fzengjin.5173.com%2fDefault.aspx'
verified_keyword: '5173'