product_url: 'https://192.168.140.28/svn_product/dlwebsites'
product_tag_dir: 'tag'
product_trunk_dir: 'trunk'
online_site_path: 'D:\com5173\dlc2c.5173.com'
app_pool: 'dlc2c.5173.com'
website_verified_url: 'http://dlc2c.5173.com/html/f5/f5.aspx'
verified_keyword: 'OK'