product_url: 'https://192.168.140.28/svn_product/dlwebsites'
product_tag_dir: 'tag'
product_trunk_dir: 'trunk'
online_site_path: 'D:\com5173\vdladmin.5173.com'
app_pool: 'vdladmin.5173.com'
website_verified_url: 'http://vdladmin.5173.com/main/AdminLogin.aspx'
verified_keyword: '´úÁ·'