product_url: 'https://192.168.140.28/svn_product/escortsites'
product_tag_dir: 'tag'
product_trunk_dir: 'trunk'
online_site_path: 'D:\danbao.5173.com'
app_pool: 'danbao.5173.com'
website_verified_url: 'http://danbao.5173.com/Html/f5/f5.aspx'
verified_keyword: 'OK'