product_url: 'https://192.168.140.28/svn_product/escortsites'
product_tag_dir: 'tag'
product_trunk_dir: 'trunk'
online_site_path: 'D:\vdbadmin.5173.com'
app_pool: 'vdbadmin.5173.com'
website_verified_url: 'http://vdbadmin.5173.com/Index.aspx?ReturnUrl=%2fhtml%2ff5%2ff5.aspx'
verified_keyword: 'ID'