product_url: 'https://192.168.140.28/svn_product/51taosites'
product_tag_dir: 'tag'
product_trunk_dir: 'trunk'
online_site_path: 'D:\51tao_new.5173.com'
app_pool: '51tao.5173.com'
website_verified_url: 'http://51tao.5173.com/Default.aspx'
verified_keyword: 'start is running'