product_url: 'https://192.168.140.28/svn_product/consignmentsites'
product_tag_dir: 'tag'
product_trunk_dir: 'trunk'
online_site_path: 'D:\com5173\consignment.5173.com'
app_pool: 'consignment.5173.com'
website_verified_url: 'http://consignment.5173.com/Html/F5/f5.aspx'
verified_keyword: 'OK'